In [1]:
import numpy as np
import pandas as pd

In [2]:
df_total = pd.read_csv('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트\\PJTJ4U\\조정범\\Data\\Dataset\\202109_주소DB_전체분\\개선_도로명코드_전체분.txt', sep = '|', encoding = 'cp949', header = None)
df_total.columns = ['도로명코드', '도로명', '도로명_로마자', '읍면동일련번호', '시도명', '시도_로마자', '시군구명', '시군구_로마자', '읍명동명', '읍면동_로마자', '읍면동구분', '읍면동코드', '사용여부', '변경사유', '변경이력정보', '고시일자', '말소일자']
df_total.drop(['도로명_로마자', '시도_로마자', '시군구_로마자', '읍면동_로마자','사용여부', '변경사유', '변경이력정보', '고시일자', '말소일자'], axis = 1, inplace = True)

In [3]:
df_total.head()

          도로명코드   도로명  읍면동일련번호    시도명 시군구명  읍명동명  읍면동구분  읍면동코드
0  111102005001  세종대로        0  서울특별시  종로구   NaN      2    NaN
1  111102005001  세종대로        1  서울특별시  종로구   세종로      1  119.0
2  111102005001  세종대로        2  서울특별시  종로구  종로1가      1  126.0
3  111102100001  삼일대로        0  서울특별시  종로구   NaN      2    NaN
4  111102100001  삼일대로        1  서울특별시  종로구   운니동      1  132.0

In [4]:
df_jibun_seoul = pd.read_csv('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트\\PJTJ4U\\조정범\\Data\\Dataset\\202109_주소DB_전체분\\지번\\지번_서울특별시.txt', sep = '|', encoding = 'cp949', header = None)
df_jibun_seoul.columns = ['관리번호', '일련번호', '법정동코드', '시도명', '시군구명', '법정읍면동명', '법정리명', '산여부', '지번(본번)', '지번(부번)', '대표여부']
# df_jibun_seoul.drop(['일련번호', '산여부'], axis = 1, inplace = True)
df_jibun_seoul

,관리번호,일련번호,법정동코드,시도명,시군구명,법정읍면동명,법정리명,산여부,지번(본번),지번(부번),대표여부
0,1111010100100010000030843,1,1111010100,서울특별시,종로구,청운동,NaN,0,1,0,1
1,1111010100100030000030936,1,1111010100,서울특별시,종로구,청운동,NaN,0,3,0,1
2,1111010100100030065030970,1,1111010100,서울특별시,종로구,청운동,NaN,0,3,100,1
3,1111010100100030065030970,2,1111010100,서울특별시,종로구,청운동,NaN,0,3,65,0
4,1111010100100030150030938,1,1111010100,서울특별시,종로구,청운동,NaN,0,3,150,1
...,...,...,...,...,...,...,...,...,...,...,...
628124,1174011000200220014000001,1,1174010300,서울특별시,강동구,상일동,NaN,1,73,0,1
628125,1174011000200220036000002,1,1174010300,서울특별시,강동구,상일동,NaN,1,77,23,1
628126,1174011000200220036000002,2,1174010300,서울특별시,강동구,상일동,NaN,0,554,15,0
628127,1174011000200220036000002,3,1174010300,서울특별시,강동구,상일동,NaN,0,554,16,0
628128,1174011000200220075000001,1,1174010300,서울특별시,강동구,상일동,NaN,1,77,38,1

In [5]:
df_jibun = pd.DataFrame(columns = ['관리번호', '일련번호', '법정동코드', '시도명', '시군구명', '법정읍면동명', '법정리명', '산여부', '지번(본번)', '지번(부번)', '대표여부'])
df_jibun

Empty DataFrame
Columns: [관리번호, 일련번호, 법정동코드, 시도명, 시군구명, 법정읍면동명, 법정리명, 산여부, 지번(본번), 지번(부번), 대표여부]
Index: []

In [6]:
df_jibun = pd.DataFrame(columns = ['관리번호', '일련번호', '법정동코드', '시도명', '시군구명', '법정읍면동명', '법정리명', '산여부', '지번(본번)', '지번(부번)', '대표여부'])
import os
path_dir = 'C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트\\PJTJ4U\\조정범\\Data\\Dataset\\202109_주소DB_전체분\\지번\\'
file_dir = os.listdir(path_dir)
n = 0
for file_name in file_dir:
    file = path_dir + file_name
    df_sample = pd.read_csv(file, sep = '|', encoding = 'cp949', header = None)
    df_sample.columns = ['관리번호', '일련번호', '법정동코드', '시도명', '시군구명', '법정읍면동명', '법정리명', '산여부', '지번(본번)', '지번(부번)', '대표여부']
    n += df_sample.shape[0]
    print(df_sample.shape, n)
    df_jibun = pd.concat([df_jibun, df_sample])

(547012, 11) 547012

C:\Users\Bestc\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

(1267223, 11) 1814235
(967512, 11) 2781747
(861809, 11) 3643556
(140154, 11) 3783710
(240855, 11) 4024565
(128712, 11) 4153277
(354737, 11) 4508014
(628129, 11) 5136143
(31720, 11) 5167863
(122564, 11) 5290427
(218640, 11) 5509067
(940765, 11) 6449832
(550144, 11) 6999976
(167843, 11) 7167819
(669651, 11) 7837470
(409697, 11) 8247167

In [7]:
df_jibun.reset_index(drop = True, inplace = True)

In [8]:
df_jibun.shape

(8247167, 11)

In [29]:
df_train = df_jibun.drop(['일련번호', '산여부', '대표여부'], axis = 1).copy()
df_train['법정리명'] = df_train['법정리명'].apply(lambda x: '0' if str(x) == 'nan' else x)
df_train['지번(본번)'] = df_train['지번(본번)'].apply(lambda x: str(x))
df_train['지번(부번)'] = df_train['지번(부번)'].apply(lambda x: str(x))
df_train['지번주소'] = df_train['시도명'] + ' ' + df_train['시군구명'] + ' ' + df_train['법정읍면동명'] + ' ' + df_train['법정리명'] + ' ' + df_train['지번(본번)'] + '-' + df_train['지번(부번)']
df_train

,관리번호,법정동코드,시도명,시군구명,법정읍면동명,법정리명,지번(본번),지번(부번),지번주소
0,4211010100100010005011491,4211010100,강원도,춘천시,봉의동,0,1,5,강원도 춘천시 봉의동 0 1-5
1,4211010100100010007011490,4211010100,강원도,춘천시,봉의동,0,1,7,강원도 춘천시 봉의동 0 1-7
2,4211010100100010008000001,4211010100,강원도,춘천시,봉의동,0,1,8,강원도 춘천시 봉의동 0 1-8
3,4211010100100010008000001,4211010700,강원도,춘천시,옥천동,0,8,6,강원도 춘천시 옥천동 0 8-6
4,4211010100100010009011489,4211010100,강원도,춘천시,봉의동,0,1,9,강원도 춘천시 봉의동 0 1-9
...,...,...,...,...,...,...,...,...,...
8247162,4380036034105910000000001,4380036034,충청북도,단양군,단성면,대잠리,591,0,충청북도 단양군 단성면 대잠리 591-0
8247163,4380036034200600000000001,4380036034,충청북도,단양군,단성면,대잠리,60,0,충청북도 단양군 단성면 대잠리 60-0
8247164,4380036034200650000000001,4380036034,충청북도,단양군,단성면,대잠리,65,0,충청북도 단양군 단성면 대잠리 65-0
8247165,4380036034200850000000001,4380036034,충청북도,단양군,단성면,대잠리,412,1,충청북도 단양군 단성면 대잠리 412-1
8247166,4380036034204490000000001,4380036034,충청북도,단양군,단성면,대잠리,449,0,충청북도 단양군 단성면 대잠리 449-0

In [30]:
df_train['지번주소'] = df_train['지번주소'].apply(lambda x: str(x).replace('0 ', ''))
df_train['지번주소'] = df_train['지번주소'].apply(lambda x: str(x).replace('-0', ''))

In [32]:
df_train

,관리번호,법정동코드,시도명,시군구명,법정읍면동명,법정리명,지번(본번),지번(부번),지번주소
0,4211010100100010005011491,4211010100,강원도,춘천시,봉의동,0,1,5,강원도 춘천시 봉의동 1-5
1,4211010100100010007011490,4211010100,강원도,춘천시,봉의동,0,1,7,강원도 춘천시 봉의동 1-7
2,4211010100100010008000001,4211010100,강원도,춘천시,봉의동,0,1,8,강원도 춘천시 봉의동 1-8
3,4211010100100010008000001,4211010700,강원도,춘천시,옥천동,0,8,6,강원도 춘천시 옥천동 8-6
4,4211010100100010009011489,4211010100,강원도,춘천시,봉의동,0,1,9,강원도 춘천시 봉의동 1-9
...,...,...,...,...,...,...,...,...,...
8247162,4380036034105910000000001,4380036034,충청북도,단양군,단성면,대잠리,591,0,충청북도 단양군 단성면 대잠리 591
8247163,4380036034200600000000001,4380036034,충청북도,단양군,단성면,대잠리,60,0,충청북도 단양군 단성면 대잠리 60
8247164,4380036034200650000000001,4380036034,충청북도,단양군,단성면,대잠리,65,0,충청북도 단양군 단성면 대잠리 65
8247165,4380036034200850000000001,4380036034,충청북도,단양군,단성면,대잠리,412,1,충청북도 단양군 단성면 대잠리 412-1
8247166,4380036034204490000000001,4380036034,충청북도,단양군,단성면,대잠리,449,0,충청북도 단양군 단성면 대잠리 449

In [33]:
df_train.to_csv('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트\\PJTJ4U\\조정범\\Data\\Dataset\\202109_주소DB_전체분\\지번\\지번주소 통합본.csv', encoding='utf-8', index = False)

In [34]:
pd.read_csv('C:/Workspace/python/빅데이터 지능형서비스 개발 팀프로젝트/PJTJ4U/조정범/Data/Dataset/202109_주소DB_전체분/지번/지번주소 통합본.csv')

C:\Users\Bestc\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,관리번호,법정동코드,시도명,시군구명,법정읍면동명,법정리명,지번(본번),지번(부번),지번주소
0,4211010100100010005011491,4211010100,강원도,춘천시,봉의동,0,1,5,강원도 춘천시 봉의동 1-5
1,4211010100100010007011490,4211010100,강원도,춘천시,봉의동,0,1,7,강원도 춘천시 봉의동 1-7
2,4211010100100010008000001,4211010100,강원도,춘천시,봉의동,0,1,8,강원도 춘천시 봉의동 1-8
3,4211010100100010008000001,4211010700,강원도,춘천시,옥천동,0,8,6,강원도 춘천시 옥천동 8-6
4,4211010100100010009011489,4211010100,강원도,춘천시,봉의동,0,1,9,강원도 춘천시 봉의동 1-9
...,...,...,...,...,...,...,...,...,...
8247162,4380036034105910000000001,4380036034,충청북도,단양군,단성면,대잠리,591,0,충청북도 단양군 단성면 대잠리 591
8247163,4380036034200600000000001,4380036034,충청북도,단양군,단성면,대잠리,60,0,충청북도 단양군 단성면 대잠리 60
8247164,4380036034200650000000001,4380036034,충청북도,단양군,단성면,대잠리,65,0,충청북도 단양군 단성면 대잠리 65
8247165,4380036034200850000000001,4380036034,충청북도,단양군,단성면,대잠리,412,1,충청북도 단양군 단성면 대잠리 412-1
8247166,4380036034204490000000001,4380036034,충청북도,단양군,단성면,대잠리,449,0,충청북도 단양군 단성면 대잠리 449