In [76]:
import numpy as np
import pandas as pd

In [77]:
df_jibun  = pd.read_csv('C:/Workspace/python/빅데이터 지능형서비스 개발 팀프로젝트/PJTJ4U/조정범/Data/Dataset/202109_주소DB_전체분/지번/지번주소 통합본.csv')
df_jibun.head()

C:\Users\Bestc\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3437: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,관리번호,법정동코드,시도명,시군구명,법정읍면동명,법정리명,지번(본번),지번(부번),지번주소
0,4211010100100010005011491,4211010100,강원도,춘천시,봉의동,0,1,5,강원도 춘천시 봉의동 1-5
1,4211010100100010007011490,4211010100,강원도,춘천시,봉의동,0,1,7,강원도 춘천시 봉의동 1-7
2,4211010100100010008000001,4211010100,강원도,춘천시,봉의동,0,1,8,강원도 춘천시 봉의동 1-8
3,4211010100100010008000001,4211010700,강원도,춘천시,옥천동,0,8,6,강원도 춘천시 옥천동 8-6
4,4211010100100010009011489,4211010100,강원도,춘천시,봉의동,0,1,9,강원도 춘천시 봉의동 1-9

In [ ]:
from tqdm.notebook import tqdm
juso_api_key = 'C:\\Workspace\\python\\Data_Science\\04.공공데이터활용\\roadapikey.txt'
import pandas as pd
with open(juso_api_key) as f:
    api_key = f.read()
import requests
from urllib.parse import quote
road_url = 'https://www.juso.go.kr/addrlink/addrLinkApi.do'

addr_list = []
df_jibun['도로명주소'] = [0 for _ in range(len(df_jibun['지번주소']))]
n = 0
for i in tqdm(range(len(df_jibun['지번주소']))):
# for i in range(100):
    try:
        option = f'confmKey={api_key}&currentPage=1&countPerPage=10&keyword={quote(df_jibun["지번주소"][i])}' # f스트링에서 &을 통해 연결
        url = f'{road_url}?{option}&resultType=json'
        result = requests.get(url).json()
        addr = result['results']['juso'][0]['roadAddr']    
        df_jibun['도로명주소'][i] = addr
    except:
        n += 1
        print(i, n)
        df_jibun['도로명주소'][i] = '검색실패'
df_jibun

In [38]:
df_jibun

,관리번호,법정동코드,시도명,시군구명,법정읍면동명,법정리명,지번(본번),지번(부번),지번주소
0,4211010100100010005011491,4211010100,강원도,춘천시,봉의동,0,1,5,강원도 춘천시 봉의동 1-5
1,4211010100100010007011490,4211010100,강원도,춘천시,봉의동,0,1,7,강원도 춘천시 봉의동 1-7
2,4211010100100010008000001,4211010100,강원도,춘천시,봉의동,0,1,8,강원도 춘천시 봉의동 1-8
3,4211010100100010008000001,4211010700,강원도,춘천시,옥천동,0,8,6,강원도 춘천시 옥천동 8-6
4,4211010100100010009011489,4211010100,강원도,춘천시,봉의동,0,1,9,강원도 춘천시 봉의동 1-9
...,...,...,...,...,...,...,...,...,...
8247162,4380036034105910000000001,4380036034,충청북도,단양군,단성면,대잠리,591,0,충청북도 단양군 단성면 대잠리 591
8247163,4380036034200600000000001,4380036034,충청북도,단양군,단성면,대잠리,60,0,충청북도 단양군 단성면 대잠리 60
8247164,4380036034200650000000001,4380036034,충청북도,단양군,단성면,대잠리,65,0,충청북도 단양군 단성면 대잠리 65
8247165,4380036034200850000000001,4380036034,충청북도,단양군,단성면,대잠리,412,1,충청북도 단양군 단성면 대잠리 412-1
8247166,4380036034204490000000001,4380036034,충청북도,단양군,단성면,대잠리,449,0,충청북도 단양군 단성면 대잠리 449

In [39]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
df_jibun['지번주소'].isnull().sum()

31720

In [41]:
df_jibun['지번주소'] = df_jibun['지번주소'].fillna('')
df_jibun['지번주소'].isnull().sum()

0

In [42]:
df_jibun['지번주소'].value_counts()

                           31720
서울특별시 노원구 상계동 161-13         257
경기도 성남시 수정구 신흥동 2467         255
전라남도 고흥군 도양읍 봉암리 2736-6      201
부산광역시 서구 아미동2가 231-181       194
                           ...
경상북도 경주시 외동읍 북토리 872-4         1
경상북도 경주시 외동읍 북토리 871           1
경상북도 경주시 외동읍 북토리 872-1         1
경상북도 경주시 외동읍 북토리 867           1
충청북도 단양군 단성면 대잠리 449           1
Name: 지번주소, Length: 7488724, dtype: int64

In [43]:
df_jibun_train = df_jibun.drop_duplicates(['지번주소'], keep = 'first').copy()

In [44]:
df_jibun_train['지번주소'].value_counts()

강원도 춘천시 봉의동 1-5            1
인천광역시 강화군 불은면 두운리 62-51    1
인천광역시 강화군 불은면 두운리 62-34    1
인천광역시 강화군 불은면 두운리 62-3     1
인천광역시 강화군 불은면 두운리 62-2     1
                          ..
경상북도 포항시 남구 대잠동 780-19     1
경상북도 포항시 남구 대잠동 780-18     1
경상북도 포항시 남구 대잠동 780-17     1
경상북도 포항시 남구 대잠동 780-16     1
충청북도 단양군 단성면 대잠리 449       1
Name: 지번주소, Length: 7488724, dtype: int64

In [64]:
df_jibun.columns

Index(['관리번호', '법정동코드', '시도명', '시군구명', '법정읍면동명', '법정리명', '지번(본번)', '지번(부번)',
       '지번주소'],
      dtype='object')

In [67]:
df_train = df_jibun_train[['시도명','시군구명','법정읍면동명','법정리명', '지번(본번)', '지번(부번)', '지번주소']].copy()

In [70]:
df_train[:10000]

       시도명 시군구명 법정읍면동명 법정리명  지번(본번)  지번(부번)               지번주소
0      강원도  춘천시    봉의동    0       1       5    강원도 춘천시 봉의동 1-5
1      강원도  춘천시    봉의동    0       1       7    강원도 춘천시 봉의동 1-7
2      강원도  춘천시    봉의동    0       1       8    강원도 춘천시 봉의동 1-8
3      강원도  춘천시    옥천동    0       8       6    강원도 춘천시 옥천동 8-6
4      강원도  춘천시    봉의동    0       1       9    강원도 춘천시 봉의동 1-9
...    ...  ...    ...  ...     ...     ...                ...
10703  강원도  춘천시    우두동    0     315       6  강원도 춘천시 우두동 315-6
10704  강원도  춘천시    우두동    0     315       7  강원도 춘천시 우두동 315-7
10705  강원도  춘천시    우두동    0     316       4  강원도 춘천시 우두동 316-4
10706  강원도  춘천시    우두동    0     316       6  강원도 춘천시 우두동 316-6
10707  강원도  춘천시    우두동    0     316       5  강원도 춘천시 우두동 316-5

[10000 rows x 7 columns]

In [75]:
import json
with open('C:\\Workspace\\python\\빅데이터 지능형서비스 개발 팀프로젝트\\PJTJ4U\\조정범\Data\\output\\한진택배_샘플.json', 'r', encoding = 'utf-8') as f:
    json_data = json.load(f)
ctg_list = []
contents_list = []
for i in range(len(json_data['images'][0]['fields'])):
    ctg_list.append(json_data['images'][0]['fields'][i]['name'])
    contents_list.append(json_data['images'][0]['fields'][i]['inferText'])
df_info = pd.DataFrame([contents_list], columns = ctg_list)
df_info

,받는분 주소1,받는분 주소2,받는분 전화번호1,받는분 전화번호2,받는분 성명,주소 보내는분1,주소 보내는분2,보내는분 전화번호1,보내는분 전화번호2,보내는분 성명
0,"광주 서구 내밤로 III , 13층",,062-111-3189,010-761-2341,따름이,부산 연제구 중앙대로 1001,24층 구축과,050 1234-567,HP010-1234-5678,타슈99